title: Your awesome title
author: MasterElysium
email: luisraisehell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  No idea.

# social links
twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username:  MasterElysium # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
